### ISSUE TITLE
FilePreference behaviour

### ISSUE THREAD

**Issue by swalladge** [EliotBerriot/django-dynamic-preferences#111]
If I upload a new file with the same name as a previously uploaded file for a particular FilePreference (in admin), the new file gets a random string added and saved, but the path given by dynamic-preferences does not include the random string.

For example, if I upload `logo.png`, the path will be given as `dynamic_preferences/image/logo.png`. Then if I upload the same file again (or another one with the same name), the file is saved as `MEDIA_ROOT/dynamic_prefences/image/logo_jktbnwmr.png`, but dynamic-preferences gives the path as `dynamic_preferences/image/logo.png`. 

I also saw a strange case where an image was uploaded to something like `dynamic_preferences/image/dynamic_preferences/image/logo.png`, but I'm not sure what I did (I misclicked on something in the admin interface), and can't reproduce it.

**Comment by EliotBerriot** [comment]
Hello and thanks for taking the time to report this. I'll have a look on it this week, unless someone else picks it first :)

**Comment by CyberFox001** [comment]
I got a similar error.

When I set the MEDIA_ROOT setting to '/media/', and use the file like that in a template:

```
<img class="forum_logo d-inline-block align-text-top" alt="logo" src="{{ global_preferences.general__forum_logo }}"/>
```

I got the URL: 
http://127.0.0.1:8000/dynamic_preferences/general__forum_logo/logo.png

Instead of having the URL:
http://127.0.0.1:8000/media/dynamic_preferences/general__forum_logo/logo.png

django-dynamic-preferences version: 1.15.0
