### ISSUE TITLE
[Question] Creating new preferences outside of dynamic_preferences_registry.py

### ISSUE THREAD

**Issue by JoLeungGitHub** [EliotBerriot/django-dynamic-preferences#181]
I was wondering if it would be possible to create/register a new preference registry in other ways than directly adding it to the `dynamic_preferences_registry.py` file, for example through Django admin or in the database.

Sorry if this has been asked or answered before I couldn't find anything on the topic.

**Comment by EliotBerriot** [comment]
Hi @JoLeungGitHub, I'm not sure I understand your question. Can you describe a bit more your use case? I'll try to answer you :)

**Comment by JoLeungGitHub** [comment]
Sorry, say I have a user that has access to the Django admin but does not have access to the codebase. Would it be possible for this user to register a new preference through the Django admin panel? (Instead of adding it to the ´django_preferences_registry.py´)

**Comment by EliotBerriot** [comment]
@JoLeungGitHub thank you for the clarification :)

No, it's not possible, and I don't see it implemented anytime soon, because having dynamic (as in: at runtime) preferences would required a complete rewrite of the package.

I think it will be simpler to use a regular django model to accomodate your use case.

**Comment by EliotBerriot** [comment]
(I'm closing because out of scope of the project, but feel free to continue the discussion here if needed)
