### ISSUE TITLE
Support for older Django versions

### ISSUE THREAD

**Issue by nick-lehmann** [EliotBerriot/django-dynamic-preferences#195]
This is not a feature but rather a question. I personally really like this package and at work, we would like to use it in a project that is running on a quite old Django version (1.4). Please do not hate me for this question, I am already punished enough :cry: 

What were the reasons support for older Django versions was dropped? Are there any real incompatibilities and is there a real blocker that prevents this app from being forked by me and made compatible with Django 1.4 while we still use this version?

**Comment by EliotBerriot** [comment]
Hi @nick-lehmann, and sorry for the delay. Supporting old versions of software requires more effort and resources, and is sometimes impossible. Since this project is maintained on a best effort basis, on my (and other contributors) free time, we cannot reasonnably support Django versions that are 6 or 7 years old (1.4 may be even older than that).

To be honest, I don't even remember if django 1.4 was still a thing when I started this package in 2014. I think the older version is worked with was django 1.7.

> Please do not hate me for this question, I am already punished enough

I understand that, however, at this point, I really thing your best course of action is to upgrade to newer version of Django :/ I don't think you'll find many (if any) maintained package that will work on Django 1.4

I wish you luck with your project anyway, I know you cannot always do as you'd like too, especially with legacy projects 

Take care

**Comment by nick-lehmann** [comment]
@EliotBerriot I totally understand your point. If not for my employer, I also wouldn't care about Django versions this old. Especially because the changes from 1.4 to 1.8 are quite huge.

>  I really think your best course of action is to upgrade to newer version of Django

You are so right. Your package was so promising and covers our use case completely. However, when we upgrade is not up to me :/ Seems like even the drop of python 2 did not cause enough pressure to upgrade..

Still very nice package. Keep up the good work 👍
