### ISSUE TITLE
Button "Add global preference" via admin does not work.

### ISSUE THREAD

**Issue by ak55mm** [EliotBerriot/django-dynamic-preferences#202]
I really liked the package. Followed the instructions given in  https://django-dynamic-preferences.readthedocs.io/en/latest/quickstart.html. The global and user preferences show up in the Django admin, all good until now.  

Next i tried the button "Add global preference" via admin. Surprisingly the form had only Raw-Value editable. The Name field was uneditable and the Section was None. How can we create a new preference without the name and section? seems like a bug.

Once the save button is clicked it says:
The Global preference “GlobalPreferenceModel - None/” was added successfully. and I see a warning:

`dynamic_preferences/registries.py:136: UserWarning: Creating a fallback preference with section "None" and name "".This means you have preferences in your database that don't match any registered preference. If you want to delete these entries, please refer to the documentation: https://django-dynamic-preferences.readthedocs.io/en/latest/lifecycle.html`

Any help would be appreciated!

Django==3.0.2
django-dynamic-preferences==1.8.1

**Comment by EliotBerriot** [comment]
Hi @ak55mm, creating new preferences via the admin isn't supported for a simple reason: your code needs to be updated in order to *use* this preference (e.g to change behaviour when this preference has a simple value, to display its content in a template, etc.). 

That's why preferences are also configured via code, in Python files, as shown here: https://django-dynamic-preferences.readthedocs.io/en/latest/quickstart.html
