### ISSUE TITLE
[Question] Localized Text preference

### ISSUE THREAD

**Issue by ondrejkolin** [EliotBerriot/django-dynamic-preferences#228]
I want to add a string which differs in every language in my Django app. Is this possible with django-dynamic-preferences?

**Comment by EliotBerriot** [comment]
We don't offer any localization mechanism, but I can see several ways to support this:

1. Create a single preferences that store the strings as a JSON object with locales as keys and translated strings as values (example : `{"en": "My string", "fr": "Ma chaîne"}`)
2. You can also create one preference per locale, but this approach is probably less flexible because you'd have to edit the code everytime you add a new locale

**Comment by ondrejkolin** [comment]
Ok, that is a fair answer to my problem!
