### ISSUE TITLE
add a file preference type

### ISSUE THREAD

**Issue by macolo** [EliotBerriot/django-dynamic-preferences#32]
For automated docker deployment I am looking for a way to move all security related info out of the project (passwords, ssl certs, api keys).

I am stuck with ssl certificates.

A file type in dynamic-preferences would allow to include a default self-signed cert in the source code of the project which could be overridden by the real certificate (using conditional configuration in the web server).

**Comment by EliotBerriot** [comment]
I'm not really sure I perfectly understand your use case, however, a file preference seems quite a good idea, even for simpler use cases, e.g storing a header or background image for a project.

I'm not sure how it would be serialized, though, I have to get a look at django's built in `models.FileField`, to get a closer idea.

**Comment by all-x** [comment]
In my project I need file preference type. Is there any chance it will be included in future release?

**Comment by EliotBerriot** [comment]
I cannot promise anything because I have a really busy schedule currently. It is definitely a feature I'd like to see implemented, but I cannot give you a date. Also, dealing with files is always more complicated than other data types, because you have to keep the filesystem in sync with the database, and I currently have no precise idea on how to implement this feature.

I keep your request in mind and will update this issue as soon as I start working on this. If someone else want to start implementing this, it's okay too :)

**Comment by fabrixxm** [comment]
Any news on merging #37 ?

**Comment by EliotBerriot** [comment]
Hello @fabrixxm and thanks for bringing this thread back to life.

There's a big rebase needed for #37, and some unit tests also. I've got some momentum working on this project over the last few days, so I'll try to keep this good mood going and implement this during for this weekend.

**Comment by EliotBerriot** [comment]
@fabrixxm The [1.2](https://pypi.python.org/pypi/django-dynamic-preferences/1.2) release including this has been pushed to PyPi ;)

**Comment by fabrixxm** [comment]
well, that was quick! :-)
Thank you, tomorrow I'll update my project requirements file 👍

**Comment by EliotBerriot** [comment]
@fabrixxm and everybody using 1.2: there is a critical bug in this version that can result in dataloss.

Please upgrade to 1.3 (at least) as soon at possible and do not use 1.2 in production.

See https://django-dynamic-preferences.readthedocs.io/en/latest/history.html#id1 for more details.

Sorry for the trouble.
