### ISSUE TITLE
Get a preference without specifying its section

### ISSUE THREAD

**Issue by philipbelesky** [EliotBerriot/django-dynamic-preferences#34]
Currently I'm getting a preference using

    instance.preferences.section_name__preference_name

However, i'd like to be able to get it in a fashion more like

    instance.preferences.preference_name

So that changes to the naming of a section, or the section value of a preference do not require reworking all of the times when I get a particular preference. Obviously this could raise an issue when two preferences have the same name, but I feel like this wouldn't be a problem for most uses. Perhaps there could be something along the lines of:

    instance.preferences.get_by_name.preference_name

Would that be a good idea? Is there already a way of doing this that I'm missing?

**Comment by EliotBerriot** [comment]
If you don't use sections, (if section is `None` on the preference conf),  you should be able to get a preference via it's name, with `instance.preferences.preference_name`. Does it solves your issue ?

**Comment by philipbelesky** [comment]
Ideally I would like to keep them having sections, as I have a large set of options and am using sections to organise them in the interface. Which is part of my problem — I'm now quite loathe to change a preference's section as I have to hunt down all the references and change them. Its not a major hassle as they are pretty unique strings, but it would be nice if it were this kind of refactoring were easier.

**Comment by EliotBerriot** [comment]
Okay, I guess it would be possible to add a `get_by_name` method on the preference manager, that would return another manager containing all references to preferences by name, and raise an exception in case of conflicts.

However, even if I understand why you need that, I'm not sure it is a good idea to hide the section part from the getter, because your code would be less explicit. Also, I'm warning you against changing section identifiers, since it is used to retrieve sections from the database.

If you change a section identifier and want to keep your previous preferences working, you'll have to make a datamigration to update the old section identifier to the new one. As you see, it's not free, so it's probably an operation you won't do often. Changing a section label or any attribute is not a problem, but you should not change identifiers unless you absolutely need it. 

I should probably insist on this part in the documentation: naming is important, sections and preferences identifiers are considered as primary keys in the code.

**Comment by philipbelesky** [comment]
Yea, I think my initial impression was that section identifiers were primarily there to organise/group preferences with an interface, rather than as primary keys. For my purposes I'd like a separation between those concerns, but I don't think that necessarily needs to be built-in — feel free to close if you agree.

**Comment by EliotBerriot** [comment]
I think it's okay , and I'd rather have a simpler API when possible, so I'm totally okay to work on this. Your use case, however, raise interesting questions : do we really need to use sections at the storage layer, or should sections only be used for a presentational purpose ?

I must admit I can't imagine any use case where someone could have the same preference name under two different sections (which was the originally designed the section system as it is today). Maybe it's time to get rid of this complexity. 

What do you think about it ?

**Comment by philipbelesky** [comment]
I would love to have a more simple method for retrieving the keys, and wouldn't mind if uniqueness was enforced at the ```name``` level. Having sections as a field is great for routing / splitting up a large form, but making it easy to change those values seems more in keeping with a presentation level concern.

**Comment by EliotBerriot** [comment]
Okay, for now, I'll focus on implementing the `get_by_key` method on the manager :)

**Comment by macolo** [comment]
While this is a minor issue in my opinion it is true that declaring a setting could be made simpler, for example by making category / name a one-string declaration.

This

```
global_preferences_registry.register
class SiteTitle(StringPreference):
    section = general
    name = 'title'
    default = 'My site'
```
could be simplified to:
```
global_preferences_registry.register
class SiteTitle(StringPreference):
    name = 'optional-category_is-divided-from_name-by_first_underscore'
    default = 'My site'
```
I think even though this is less explicit it would improve the developer experience.

Still, in Django Admin the current behaviour of having a section column should be maintained, as the filter box that displays all categories is really handy.

What concerns me far more in regards to setting name / category is #35

**Comment by EliotBerriot** [comment]
@macolo, I'm not sure declaring sections via a prefix in the name, instead of binding the actual `Section` object would work correctly in all cases. If we don't import it explicitely when we declare preferences, it mean I have to make another registry that will import sections before importing preferences, and that you have to prefix all sections with a `sections.register` decorator.

Still, it's shorter to decorate sections object once, and then use the section identifier when registering preference, but I'd rather avoid firing another registry / autodiscovering process if possible. The drawback of manually importing a section and mapping it to the corresponding attribute on the preference seems bearable to me, especially since most of the time, you'll have the section already defined in the file.

Implementing this will also be bound to the decision we make about sections : are they purely presentational or do they need to be persisted in database ?

If you still want this to get implemented, please open a dedicated issue, I'll take some time to consider it :)
