### ISSUE TITLE
ImportError when application configuration class is specified in INSTALLED_APPS

### ISSUE THREAD

**Issue by all-x** [EliotBerriot/django-dynamic-preferences#50]
python 3.5.1 windows x64
Django==1.9.4
django-dynamic-preferences==0.8.1
persisting-theory==0.2.1

When in I specify application configuration class myapp.apps.MyAppConfig instead of application package in INSTALLED_APPS there is ImportError:

  File "C:\Tools\Python3\lib\site-packages\dynamic_preferences\apps.py", line 19, in ready
    global_preferences_registry.autodiscover(settings.INSTALLED_APPS)
  File "C:\Tools\Python3\lib\site-packages\persisting_theory\registries.py", line 102, in autodiscover
    app_package = **import**(app)
ImportError: No module named 'myapp.apps.MyAppConfig'; 'myapp.apps' is not a package

When I specify only 'myapp' package there is no ImportError, but I can't set verbose_name etc for my application.

I'm rather new to Python and may be the question is stupid (or related to persisting_theory, not dynamic_preferences) but I stuck on it and need help.

**Comment by EliotBerriot** [comment]
Can you please share your project layout and the content of `myapp/__init__.py` and `myapps/apps.py`?

**Comment by all-x** [comment]
I've tried fresh django site from tutorial with only one [almost] empty app.

__init__.py is empty.

apps.py:
```
from django.apps import AppConfig
from django.utils.translation import ugettext_lazy as _


class MyappConfig(AppConfig):
  name = 'myapp'
  verbose_name = _('MyApp')

```

I suspect it is about python path, not app content.

**Comment by EliotBerriot** [comment]
There is indeed a problem here, since dynamic-preferences try to import the `dynamic_preferences_registry` file from your `apps` file.

The short term solution would be to add this to your `myapp/__init__.py`:

```python
default_app_config = 'myapp.apps.MyAppConfig'
```

and update your settings:

```python
INSTALLED_APPS = [
    # 'myapp.apps.MyAppConfig', remove this
    'myapp',
]
```

It should fix your import error, while keeping your app configuration. Nothing fancy here, the `default_app_config` in `__init__` is a regular django mechanism, [as described in the documentation](https://docs.djangoproject.com/ja/1.9/ref/applications/#configuring-applications).

However, I'll keep this issue open until a decision is made about supporting this kind of app delcaration or not. It seems really tricky to me, but maybe someone will come with an idea ?

**Comment by martianrock** [comment]
providing default_app_config only works if it is myapp, if it is an_app_installed_by_pip_into_site_packages_dir modifying its apps.py becomes tricky.
Also, the docs state:
"""
New applications should avoid default_app_config. Instead they should require the dotted path to the appropriate AppConfig subclass to be configured explicitly in INSTALLED_APPS.
"""
and
"""
Your code should never access INSTALLED_APPS directly. Use django.apps.apps instead.
"""
If you want ideas, how about this one: 
django,apps.apps.app_configs is an ordered set of appconfigs, may be you can do 
os.path.join(django.apps.apps.app_configs['myapp'].path, 'dynamic_preferences_registry') and try to import that using importlib or imp?

**Comment by EliotBerriot** [comment]
I agree I may have done a mistake regarding the path handling. Would you mind providing a Pull Request to adress this ? I'd be more than happy to merge a fix for my dirty hacks ;)

**Comment by martianrock** [comment]
correct me if I'm wrong, but actual import happens in autodiscover method in persisting-theory project outside of this repository, I found one in gitlab, is this the latest revision?

**Comment by EliotBerriot** [comment]
You're right, this is another project of mine that was not migrated to GitHub (and the Gitlab instance used is private). Persisting-theory is not specifically targeted at Django projects, so we could probably write some helper function to help with handling django apps paths. 

However, the Gitlab to GitHub migration is not something I want to deal with now, so I'd rather seen something done on django-dynamic-preferences side. As you suggested, that would probably mean constructing a list of apps paths and passing it to the [`autodiscover`](https://github.com/EliotBerriot/django-dynamic-preferences/blob/develop/dynamic_preferences/apps.py#L19) call instead of `settings.INSTALLED_APPS`. 

Is it okay for you to work on that by submitting a PR on django-dynamic-preferences ?

If that works as expected, I can then port that in persisting-theory (probably using a dedicated Registry class, targeted at django projects).
