### ISSUE TITLE
Invalidate cache on all post_save signals?

### ISSUE THREAD

**Issue by phoebebright** [EliotBerriot/django-dynamic-preferences#66]
In models.py invalidate_cache is called on all model saves:

     post_save.connect(invalidate_cache)

Should it be this?

    post_save.connect(invalidate_cache, sender=UserPreferenceModel)
    post_save.connect(invalidate_cache, sender=PerInstancePreferenceModel)
    post_save.connect(invalidate_cache, sender=GlobalPreferenceModel)

I found this when trying to work out how to invalidate template cache on UserPreferenceModel update as I'm caching template fragments that need to be cleared if the user changes their preferences.  My plan is to connect to the post_save signal and call an additional invalidate cache routine.

**Comment by EliotBerriot** [comment]
As you can see in the [models file](https://github.com/EliotBerriot/django-dynamic-preferences/blob/develop/dynamic_preferences/models.py#L135), before doing anything in the `invalidate_cache` function, we check that the saved instance is actually a preference.

I agree, this may be better to explicitely bind each signal to specific class, but it would make the setup more difficult for people wo want to bind preferences to their own models. The overhead should be quite small, but if you have any benchmark showing a significant impact, I'm okay to work on that.

Regarding the template issue, one way to achieve that would be to add a `last_update` field on preferences models, and to use this new field as a fragment of the cache key.

However, since most access to the preferences are directly done on the value (and not on the underlying database object), this would mean implementing something else to access this new field as well.

Another way to do it, without touching anything in dynamic_preferences, would be to add a `preferences_last_updated` on your User model, and update this field each time a preference is saved, by binding to the post_save signal of UserPreferenceModel. However, it's less accurate, because it does not allow for per preference template caching.

I do not have much time to work on this right now, but if you want to submit a PR regarding this, I'd be more than happy to help you sort this out :)

**Comment by EliotBerriot** [comment]
I'm closing, feel free to reopen if you want to work on this.
