### ISSUE TITLE
checkpreferences no longer deletes obsolete preferences

### ISSUE THREAD

**Issue by czlee** [EliotBerriot/django-dynamic-preferences#75]
I apologize for not picking up on this while reviewing #68, but I think `checkpreferences` might not actually delete obsolete preferences now that the fallback preference is in place. I think (but am not 100% sure) that the root cause is because the line `pref = p.preference` in [checkpreferences.py:18](https://github.com/EliotBerriot/django-dynamic-preferences/blob/develop/dynamic_preferences/management/commands/checkpreferences.py#L18) no longer raises a KeyError, since it's now designed to return a fallback preference if it didn't exist, so it returns the fallback preference without exception.

I'd submit a pull request but the solution isn't obvious to me, at least not what would be consistent with the structure you have in mind.

**Comment by EliotBerriot** [comment]
Yep, it seems I forgot to write a test somewhere...

I think one way to fix this could be to add a `_IS_FALLBACK = True` attribute to the [`MissingPreference`](https://github.com/EliotBerriot/django-dynamic-preferences/blob/develop/dynamic_preferences/registries.py#L22) class which is used as a fallback. This way, instead of calling `p.preference` to check if a preference is missing, we could do:

```python

try:
    if p.preference._IS_FALLBACK:
        p.delete()
        deleted.append(p)
except AttributeError:
    continue
```
