### ISSUE TITLE
Help creating preferences on the fly

### ISSUE THREAD

**Issue by n3storm** [EliotBerriot/django-dynamic-preferences#76]
I am trying to create a queryset filter on the fly per model and per user.

All my ListViews inherit from a class that has a filters(self) property. In that section I want to create a preference for queryset filters using django-filter module.

I have found several issues with my approach:

```
def filters(self):
            self.filter_name = self.model.__name__ + "FilterSet"
            self.filter_preference_name = "%s_%s_filter" % (self.model._meta.app_label, self.filter_name.lower())
            self.filter_preference_full_name = "Personal__%s_%s_filter" % (self.model._meta.app_label, self.filter_name.lower())
            self.filter_preference_class_name = "FilterPreference%s%s" % (self.model._meta.app_label.title(), self.filter_name)
            if self.filter_preference_full_name not in preferences_manager.keys():
                FilterPref = type(str(self.filter_preference_class_name), (StringPreference,), {
                'section':personal,
                'name':self.filter_preference_name,
                'default': '{}',
                'instance': self.request.user,
                 })
                user_preferences_registry.register(FilterPref)
```

Some times preference is created but not persistent. When I change from /myob/list to /anotherobj/list myobj list disappears.
Some times preference is not created at first time, and is created after a second reload.

I also have tried creating preference using orm like in tests and does not persist: ```UserPreferenceModel.objects.get_or_create(
                instance=self.henri,
                section="misc",
name='is_zombie')[0].value)```

I would not like to create a dynamic_preferences_registry files and objects for more than 30 models, plus I am planning to set settings also for tables: per_page and list_mode (table, cards, ...)

Any ideas why my approach is wrong? is it possible?

Thanks in advance.

**Comment by n3storm** [comment]
Update: database records are created properly

**Comment by n3storm** [comment]
Update: looks like what is happening is that ```user_preferences_registry.register(FilterPref)``` is not working

**Comment by n3storm** [comment]
This doesn't work either. 
        ´´´
       def filters(self):
            @user_preferences_registry.register
            class FilterPref(StringPreference):
                section = personal
                name = self.filter_preference_name
                default = '{}'´´´

**Comment by EliotBerriot** [comment]
This code:

```
@user_preferences_registry.register
class FilterPref(StringPreference):
    section = personal
    name = self.filter_preference_name
    default = '{}'
```

Should be put at the root of the `dynamic_preferences_registry.py` file in your app. In your example, it is nested in a `def filters(self)` function definition, meaning it is not registered until you actually call that function.

Can you try that and tell me if it works?

**Comment by EliotBerriot** [comment]
But I suspect your problem here is that you try to register preferences dynamically after your server started. This is maybe possible, but not explicitely supported by this project: you have to declare preferences statically (you can use inheritance and mixins, though) so they are picked up and loaded during the apps loading.

You can do that, and still use that dynamical approach of yours to filter preferences in a view, though.

**Comment by n3storm** [comment]
Your last comment is right. I ended up at your PersistenceTheory module skimming through autodiscover code and looks like registering only works on stated module files as you pointed.

**Comment by n3storm** [comment]
I managed to do it (in part) in a dynamic_preferences_registry.py file:

```
from django.apps import apps
for model in apps.get_models():
    filter_name = model.__name__ + "FilterSet"
    #~ if filter_preference_full_name not in preferences_manager.keys():
    @user_preferences_registry.register
    class FilterPref(StringPreference):
        section = personal
        name = filter_preference_name
        default = '{}'
```
But this method is outside django app_ready so not all apps are available and not a preference is created and registred for all models.

**Comment by EliotBerriot** [comment]
You probably don't want to register these preferences for *all* django models, because this will include models such as ContentType or models that are usually not used directly by users.

If you really want to do that, though, the best think you can do is to put `dynamic_preferences` at the end of `INSTALLED_APPS` . This will mean registry population will only be triggered once all previous apps are loaded, so your `dynamic_preferences_registry.py` will be able to dynamically instanciate a preference for all previously registered apps models.

However, unless you really want to have this preference available for all models, I strongly suggest you explicitely declare those preferences.

You can create a function to do this (pseudocode):
```python

def create_filter_pref(model):
    filter_name = model.__name__ + "FilterSet"

    @user_preferences_registry.register
    class FilterPref(StringPreference):
        section = personal
        name = filter_name
        default = '{}'

from myapp import models

create_filter_pref(models.MyModel1)
create_filter_pref(models.MyModel2)
```

This way you can explicitely enable / disable a preference for a given model, and you don't rely on the autodiscovering order.

**Comment by n3storm** [comment]
Your pseudo code is meant to be placed in a dynamic_preferences_registry.py file too?

**Comment by EliotBerriot** [comment]
Yes : everything related to preferences should be put in that file.

If the problem persists, can you pelase open a dedicated issue and reference this one, since we're on a closed pull requests here ;)

**Comment by n3storm** [comment]
I proceed to close the issue.
Thank you so much, Eliot!

**Comment by EliotBerriot** [comment]
I'm really sorry, I've mixed up two conversations (#77 was happening on a PR). Since this thread was in an issue, and not in a PR, you can totally reopen it and I'll help you until your problem is solved, if it's not solved already.
